/**
 * Zod schemas for every durable record of the agent-teams storage domain.
 * The same schemas validate the harness storage domain at its durable
 * boundary (see `src/harness/domain.ts`).
 * @module dsh-agent-teams/core
 */
import { z } from 'zod';
export const sessionIdSchema = z.string().min(1);
export const idSchema = z.string().min(1);
export const teamSchema = z.object({
    id: idSchema,
    name: z.string().min(1).max(120),
    goal: z.string().min(1).max(4000),
    leadSessionId: sessionIdSchema,
    workspaceId: z.string(),
    status: z.enum(['active', 'paused', 'completed', 'failed']),
    createdAt: z.number(),
    updatedAt: z.number(),
});
export const memberSchema = z.object({
    id: idSchema,
    teamId: idSchema,
    sessionId: sessionIdSchema,
    name: z.string().min(1).max(80),
    role: z.string().min(1).max(80),
    status: z.enum(['starting', 'working', 'idle', 'blocked', 'reviewing', 'stopped', 'failed']),
    lifecycleState: z.enum(['starting', 'ready', 'waiting_for_task', 'claiming', 'working', 'reporting', 'blocked', 'waiting_for_review', 'stopped', 'failed', 'cancelled']).optional(),
    currentTaskId: idSchema.optional(),
    provider: z.string().optional(),
    modelProvider: z.string().optional(),
    model: z.string().optional(),
    capabilities: z.array(z.string()).optional(),
    workspaceId: z.string().optional(),
    eventCursor: z.number().int().nonnegative().optional(),
    version: z.number().int().positive().optional(),
    joinedAt: z.number(),
    lastActiveAt: z.number(),
});
export const taskSchema = z.object({
    id: idSchema,
    teamId: idSchema,
    title: z.string().min(1).max(200),
    description: z.string().max(8000),
    status: z.enum(['pending', 'in_progress', 'blocked', 'completed', 'failed', 'cancelled']),
    priority: z.enum(['critical', 'high', 'normal', 'low']),
    availability: z.enum(['locked', 'ready']).optional(),
    ownerSessionId: sessionIdSchema.optional(),
    assignedMemberId: idSchema.optional(),
    assignedRole: z.string().max(80).optional(),
    requiredCapabilities: z.array(z.string()).optional(),
    workspaceId: z.string().optional(),
    dependencies: z.array(idSchema),
    requiresPlan: z.boolean(),
    required: z.boolean(),
    result: z.string().max(12000).optional(),
    createdAt: z.number(),
    startedAt: z.number().optional(),
    completedAt: z.number().optional(),
});
export const messageSchema = z.object({
    id: idSchema,
    teamId: idSchema,
    fromSessionId: sessionIdSchema,
    toSessionId: sessionIdSchema.optional(),
    type: z.enum(['message', 'question', 'result', 'warning', 'handoff', 'review', 'plan', 'shutdown']),
    body: z.string().min(1).max(16000),
    createdAt: z.number(),
    deliveryState: z.enum(['pending', 'queued', 'delivering', 'delivered', 'acknowledged', 'failed']).optional(),
    deliveryTransport: z.enum(['native-followup', 'native-report', 'durable-inbox']).optional(),
    deliveryAttempt: z.number().int().nonnegative().optional(),
    deliveryTargets: z.record(z.string(), z.object({
        state: z.enum(['pending', 'queued', 'delivering', 'delivered', 'acknowledged', 'failed']),
        attempts: z.number().int().nonnegative(),
        deliveredAt: z.number().optional(),
        error: z.string().max(4000).optional(),
    })).optional(),
    deliveredAt: z.number().optional(),
    deliveryError: z.string().max(4000).optional(),
});
export const planSchema = z.object({
    id: idSchema,
    teamId: idSchema,
    taskId: idSchema,
    authorSessionId: sessionIdSchema,
    body: z.string().min(1).max(30000),
    status: z.enum(['submitted', 'approved', 'rejected']),
    feedback: z.string().max(8000).optional(),
    createdAt: z.number(),
    reviewedAt: z.number().optional(),
});
export const fileClaimSchema = z.object({
    id: idSchema,
    teamId: idSchema,
    ownerSessionId: sessionIdSchema,
    ownerMemberId: idSchema.optional(),
    pattern: z.string().min(1).max(500),
    kind: z.enum(['file', 'directory', 'glob']),
    purpose: z.string().max(500),
    createdAt: z.number(),
});
export const findingSchema = z.object({
    id: idSchema,
    teamId: idSchema,
    authorSessionId: sessionIdSchema,
    taskId: idSchema.optional(),
    severity: z.enum(['critical', 'high', 'medium', 'low']),
    summary: z.string().min(1).max(300),
    detail: z.string().max(8000),
    title: z.string().max(300).optional(),
    description: z.string().max(8000).optional(),
    evidence: z.string().max(12000).optional(),
    responsibleMemberId: idSchema.optional(),
    state: z.enum(['open', 'resolved', 'accepted']),
    createdAt: z.number(),
    resolvedAt: z.number().optional(),
});
export const workspaceSchema = z.object({
    id: idSchema,
    teamId: idSchema,
    memberId: idSchema.optional(),
    taskId: idSchema.optional(),
    repositoryRoot: z.string().min(1),
    branch: z.string().min(1),
    worktreePath: z.string().min(1),
    status: z.enum(['requested', 'creating', 'ready', 'dirty', 'clean', 'review', 'merged', 'abandoned', 'recoverable']),
    leaseId: idSchema,
    createdAt: z.number(),
    updatedAt: z.number(),
    lastHeartbeatAt: z.number(),
});
export const gitWorkspaceSchema = z.object({
    id: idSchema,
    workspaceId: idSchema,
    repositoryRoot: z.string().min(1),
    branch: z.string().min(1),
    baseRef: z.string().min(1),
    worktreePath: z.string().min(1),
    head: z.string().optional(),
    changedFiles: z.array(z.string()),
    status: z.enum(['creating', 'ready', 'dirty', 'clean', 'merged', 'abandoned', 'recoverable']),
    createdAt: z.number(),
    updatedAt: z.number(),
});
export const workspaceCommitSchema = z.object({
    id: idSchema,
    teamId: idSchema,
    workspaceId: idSchema,
    memberId: idSchema,
    taskId: idSchema.optional(),
    hash: z.string().min(1),
    subject: z.string().min(1),
    files: z.array(z.string()),
    createdAt: z.number(),
});
/** Compatibility alias for callers that refer to the table as commits. */
export const commitSchema = workspaceCommitSchema;
export const reviewRequestSchema = z.object({
    id: idSchema,
    teamId: idSchema,
    taskId: idSchema,
    workspaceId: idSchema,
    requestedBy: sessionIdSchema,
    reviewerMemberId: idSchema,
    baseRef: z.string().min(1),
    headRef: z.string().min(1),
    status: z.enum(['requested', 'in_review', 'changes_requested', 'approved', 'rejected']),
    createdAt: z.number(),
    updatedAt: z.number(),
});
export const reviewResultSchema = z.object({
    id: idSchema,
    requestId: idSchema,
    reviewerMemberId: idSchema,
    verdict: z.enum(['approved', 'changes_requested', 'rejected']),
    evidence: z.array(z.string()),
    findingIds: z.array(idSchema),
    createdAt: z.number(),
});
export const runtimeEventSchema = z.object({
    id: idSchema,
    teamId: idSchema,
    sequence: z.number(),
    name: z.string().min(1),
    actorSessionId: sessionIdSchema.optional(),
    targetSessionId: sessionIdSchema.optional(),
    visibility: z.enum(['public', 'internal']),
    payloadVersion: z.literal(1),
    dedupeKey: z.string().optional(),
    payload: z.record(z.string(), z.unknown()),
    createdAt: z.number(),
});
export const domainSchema = {
    teams: teamSchema,
    members: memberSchema,
    tasks: taskSchema,
    messages: messageSchema,
    plans: planSchema,
    file_claims: fileClaimSchema,
    findings: findingSchema,
    workspaces: workspaceSchema,
    git_workspaces: gitWorkspaceSchema,
    commits: workspaceCommitSchema,
    review_requests: reviewRequestSchema,
    review_results: reviewResultSchema,
    runtime_events: runtimeEventSchema,
};
